version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '180:80'
      - '181:81'
      - '1443:443'
    volumes:
      - nginx-proxy-manager-data:/data:rw
      - nginx-proxy-manager-certs:/etc/letsencrypt:rw
volumes:
  nginx-proxy-manager-data:
  nginx-proxy-manager-certs:

